### ISSUE TITLE
Data Hygiene clarity

### ISSUE THREAD

**Issue by rmacrae-at-adobe-com** [AdobeDocs/experience-platform.en#144]
Issue in ./help/hygiene/home.md

Hi,

This page says that Data Hygiene, which defacto is defined as 

1. Scheduling automated dataset expirations
2. Deleting consumer data based on ingested identities

is only available to organizations that have signed up for Healthcare Shield or Privacy & Security Shield

Is that definitely the case?  I believed both features were foundational and available to all (although you get more concurrent Dataset expiration requests if you have one of the Shield queues).  This is causing internal confusion and it conflicts with the following https://fieldreadiness-adobe.highspot.com/items/635834aef8eacf8eae48be8f?lfrm=shp.2#1

For item 2 above "Deleting consumer data based on ingested identities" this in fact means responding to a GDPR-style request from a consumer who wishes to access or delete their data.  Is that correct?  I think we should make this explicitly clear up front.  This is not really a "cleaning" of data, it's a compliance related feature, so this is more scope for confusion.  Describing this as "Deleting consumer data based on ingested identities" could be misleading.

Finally, the GDPR and Privacy Service UI documentation makes no mention of having to be licensed for Privacy & Security Shield.
https://experienceleague.adobe.com/docs/experience-platform/privacy/home.html?lang=en
https://experienceleague.adobe.com/docs/experience-platform/privacy/ui/overview.html?lang=en

Thank you.

Ross

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137905.

**Comment by vfalon** [comment]
@rmacrae-at-adobe-com we've reviewed the documentation, and made some clarifications. A few notes on this update:

1. Hygiene is still only available for Healthcare Shield and Privacy & Security Shield today. There are indeed plans to deliver the foundational pieces of Hygiene to all customers as described, but due to the delta lake migration this has been delayed until next year.
2. This wasn't really addressed well in the docs, but consumer deletes are only to be used for data cleansing, removing anonymous data, and/or data minimization. All data subject rights requests (compliance) must be sent to Privacy Service instead. We've adjusted the language around consumer deletes in the docs to reflect this, along with disclaimers that point out the different use cases between consumer deletes and privacy requests, e.g.: https://experienceleague.adobe.com/docs/experience-platform/hygiene/home.html 
3. Privacy Service is a foundational ExC feature and is not restricted to any particular SKU or product. Any user w/ administrator rights in an Org that has access to Experience Cloud products will be able to leverage Privacy Service capabilities.
