### ISSUE TITLE
Timestamp description

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#27]
Issue in help/xdm/schema/field-dictionary.md

This document looks dated - it does not have all the XDM fields present and the descriptions are not accurate.
For example below is the description for timestamp

xdm:timestamp | Timestamp | The timestamp when the retargeting entity, such as aam-segment, was synced to the marketing platform.
-- | -- | --

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-69708

**Comment by pnolan89** [comment]
@nhecht This table is automatically generated/populated based on the field descriptions provided in the XDM repo, which we do not have direct control over. While we can re-run the script to add any new fields, the descriptions will remain the same and would be very difficult to maintain manually.

The field dictionary in general has become less and less useful as XDM has moved toward mixins rather than having a single schema containing all fields that can be found in the dictionary. As part of the effort to restructure the XDM docs based on our other conversation (tracked in https://jira.corp.adobe.com/browse/PLAT-69687), we are planning to create mixin-focused docs that contain more curated, contextualized descriptions of common fields like `xdm:timestamp`.

**Comment by nhecht** [comment]
Sounds good Peter, thank you for the context. Makes sense to focus the effort on the mixin documentation.

-Nick

**Comment by djwendo** [comment]
@nhecht and/or @pnolan89, am I okay to close this issue as we're transitioning to a new document as tracked in PLAT-69687?

**Comment by nhecht** [comment]
Hi Wendy,

Yes, ok from my end.

Nick Hecht  |  Sr. Platform Architect  |  Adobe Experience Platform
