### ISSUE TITLE
No Search results for "customer journey analytics" 

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#39]
Search for "customer journey analytics" does not return any results on the help documentation

https://docs.adobe.com/content/help/en/experience-platform

**Comment by djwendo** [comment]
Searching for Customer Journey Analytics doesn't return a full set of results because the CJA documentation resides in its own help guide. This is a known limitation in the current search functionality that will hopefully be resolved soon.

CJA documentation can be found here: https://docs.adobe.com/content/help/en/analytics-platform/using/cja-landing.html

**Comment by iandejong** [comment]
Hi Wendy
 Can you please re open the ticket until the issue has been confirmed to be
resolved after the release.

 closing before the issue is actually fixed could leave gaps and remaining
issues if not confirmed before closing.

Thanks
Ian
