### ISSUE TITLE
Not able to delete callback 

### ISSUE THREAD

**Issue by PranithaKatta** [AdobeDocs/experience-platform.en#46]
Issue in ./help/tags/api/endpoints/callbacks.md
. I’ve created a callback for launch audit events specific to our Launch web property using reactor API. Now when I’m trying to delete them, the API call is always returning 404 response instead of 204. All of the required parameters for the call like org id, client key, bearer token and endpoint are valid and I’m able to use them for retrieving callback details. 
![image](https://user-images.githubusercontent.com/104070900/164216182-cee3d674-4ed7-4e7a-814b-8078608ccfa9.png)

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-121641.

**Comment by PranithaKatta** [comment]
@vfalon any update on this ?

**Comment by vfalon** [comment]
@PranithaKatta we've reviewed and tested the documentation sample and the API call is working correctly. Judging from the info provided in the GitHub issue, it seems that you are missing the correct `accept` and `content-type` headers. Please review the documentation thoroughly and try the API call again. Closing this issue, since the documentation was validated.
