### ISSUE TITLE
Definition of exited in segmentMembership

### ISSUE THREAD

**Issue by chetanmeh** [AdobeDocs/experience-platform.en#52]
Issue in ./help/xdm/field-groups/profile/segmentation.md

> exited: The profile is exiting the segment as part of the current request.

Is this number based on last run or is this absolute i.e. total number of profile which were at any point in time were part of segment and now not

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-PLAT-124070.

**Comment by vgiurgiu** [comment]
@chetanmeh - The field in question (xdm:status) is actually a string field, and represents the status of the segment membership for one particular profile rather than a profile membership count for a particular segment.

That said, we updated the page in question (https://experienceleague.adobe.com/docs/experience-platform/xdm/field-groups/profile/segmentation.html) to clearly mention that the field is a sting. 

Closing this issue. Please re-open this issue or create a new one if you have further questions.
