### ISSUE TITLE
Restriction on segment changes

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/experience-platform.en#55]
Issue in ./help/segmentation/ui/segment-builder.md

Based on my experience, if you try to change a segment with a specific evaluation method (like Edge for example) and the new changes does not match, the UI returns a error. 
This means that the evaluation method is not changeable and also the changes should fit the original evaluation method. Can you please add these alert in the documentation?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-124068.

**Comment by vgiurgiu** [comment]
Closing this issue, since we now have the option (and accompanying documentation) to switch between evaluation methods. @angeli-adobe, please reopen if needed. 

Documentation about selecting between various segment evaluation methods is here: https://experienceleague.adobe.com/docs/experience-platform/segmentation/ui/segment-builder.html?lang=en#segment-properties
